[package]
name = "regex-test"
version = "0.1.0"
edition.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.11.1"
pcre2 = "0.2.10"
onig = "6.4.0"
re2 = { version = "0.0.11", optional = true }
